apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-gcp-ejemplo
  namespace: argocd
spec:
  project: microservices-gcp
  source:
    repoURL: 'https://github.com/jesusgitops-netizen/microservices-gcp-ejemplo.git'
    targetRevision: main
    path: release
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
